# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fl1pzinn
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: apisls
# "service" is the name of this project. This will also be added to your AWS resource names.
service: apisls

plugins:
  - serverless-offline 

package:
  individually: true 

build:
  esbuild:
    minify: true
    platform: node
    target: node20 
    exclude:
      - '@aws-sdk/*'


provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - !GetAtt CarsTable.Arn

functions:
  ListCars:
    handler: src/functions/listCars.handler
    events:
      - httpApi:
          path: /cars
          method: get
  GetCar:
    handler: src/functions/getCar.handler
    events:
      - httpApi:
          path: /cars/{carId}
          method: get
  CreateCar:
    handler: src/functions/createCar.handler
    events:
      - httpApi:
          path: /cars
          method: post
  UpdateCar:
    handler: src/functions/updateCar.handler
    events:
      - httpApi:
          path: /cars/{carId}
          method: put
  DeleteCar:
    handler: src/functions/deleteCar.handler
    events:
      - httpApi:
          path: /cars/{carId}
          method: delete


resources:
  Resources:
    CarsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CarsTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions: # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey
          - AttributeName: id 
            AttributeType: S # S for String
        KeySchema:
          - AttributeName: id 
            KeyType: HASH # HASH for Partition Key
            # - AttributeName: name
            #   KeyType: RANGE # RANGE for Sort Key


